title: "[I used] "
labels: ["tool"]
body:
  - type: dropdown
    id: pros
    attributes:
      label: Pros
      description: You may select more than one.
      multiple: true
      options:
        - Performance
        - Ease of use
        - Cost-effective
        - Feature-rich
        - Scalability
        - Security
      default: 0
    validations:
      required: true
  - type: input
    id: more
    attributes:
      label: Other
      description: "More reasons to like this"
      placeholder: "..."
    validations:
      required: true
  - type: checkboxes
    id: cons
    attributes:
      label: Cons
      description: You may select more than one.
      options:
        - label: Steep learning curve
        - label: Limited compatibility
        - label: Expensive
        - label: Outdated features
        - label: Poor customer support
  - type: input
    id: less
    attributes:
      label: Other
      description: "Less reasons to like this"
      placeholder: "..."
    validations:
      required: true
