title: Tool Review Form
description: Share your thoughts on a tool you've used
category: tools
fields:
  - type: text
    name: tool_name
    label: Tool Name
    description: Enter the name of the tool you're reviewing
  - type: url
    name: tool_url
    label: Tool URL
    description: Provide the official website or documentation link
  - type: url
    name: tool_repo
    label: Tool Repo
    description: Provide the source code repository link
  - type: checkbox_list
    name: pros
    label: Pros
    description: Check the advantages you found using this tool
    options:
      - Performance
      - Ease of use
      - Cost-effective
      - Feature-rich
      - Scalability
      - Security
      - Other (please specify below)
      - label: Other
        placeholder: "Enter another advantage"
  - type: checkbox_list
    name: cons
    label: Cons
    description: Check the disadvantages you experienced
    options:
      - Steep learning curve
      - Limited compatibility
      - Expensive
      - Outdated features
      - Poor customer support
      - Other (please specify below)
      - label: Other
        placeholder: "Enter another disadvantage"
  - type: text
    name: image_link
    label: Image Link (Optional)
    description: Add an image link if available
