title: Toolstore
labels: ["tool"]
body:
  - type: checkboxes
    id: pros
    attributes:
      label: Pros
      description: You may select more than one.
      options:
        - Performance
        - Ease of use
        - Cost-effective
        - Feature-rich
        - Scalability
        - Security
  - type: input
    id: more
    attributes:
      label: Other
      description: "Moer reasons to like this"
      placeholder: "[ ... ]"
    validations:
      required: true
