title: "[I used] "
labels: ["tool"]
body:
  - type: input
    id: url
    attributes:
      label: Link
      description: "Provide the official website or documentation link"
      placeholder: "http://.."
  - type: input
    id: repo
    attributes:
      label: Repository
      description: "Provide the source code repository link"
      placeholder: "http://.."
  - type: dropdown
    id: env
    attributes:
      label: Environment
      description: You may select more than one.
      multiple: true
      options:
        - MacOS
        - Linux
        - Windows
        - Python
        - JavaScript
        - Julia
        - Java
        - R
  - type: dropdown
    id: pros
    attributes:
      label: Pros
      description: You may select more than one.
      multiple: true
      options:
        - Performance
        - Ease of use
        - Cost-effective
        - Feature-rich
        - Scalability
        - Security
      default: 1
    validations:
      required: true
  - type: input
    id: more
    attributes:
      label: Other
      description: "More reasons to like this"
      placeholder: "..."
    validations:
      required: true
  - type: dropdown
    id: cons
    attributes:
      label: Cons
      description: You may select more than one.
      multiple: true
      options:
        - Steep learning curve
        - Limited compatibility
        - Expensive
        - Outdated features
        - Poor customer support
    validations:
      required: true
  - type: input
    id: less
    attributes:
      label: Other
      description: "Less reasons to like this"
      placeholder: "..."
    validations:
      required: true
