title: "[I used] "
labels: ["tool"]
body:
  - type: markdown
    attributes: 
      value: "## Info"
  - type: input
    id: url
    attributes:
      label: URL
      description: "Provide the official website or documentation link"
      placeholder: "https://.."
  - type: input
    id: repo
    attributes:
      label: Repository
      description: "Provide the source code repository link"
      placeholder: "https://.."
  - type: markdown
    attributes: 
      value: "##"
  - type: dropdown
    id: pros
    attributes:
      # description: You may select more than one.
      label: "Pros"
      multiple: true
      options:
        - Performance
        - Ease of use
        - Cost-effective
        - Feature-rich
        - Scalable
      default: 1
    validations:
      required: true
  - type: input
    id: more
    attributes:
      label: "More"
      # description: "More reasons to like this."
      placeholder: "..."
  - type: markdown
    attributes: 
      value: "##"
  - type: dropdown
    attributes:
      label: "Cons"
      # description: You may select more than one.
      multiple: true
      options:
        - Steep learning curve
        - Limited compatibility
        - Costs of usage
        - Outdated features
        - Poor support
    validations:
      required: true
  - type: input
    id: less
    attributes:
      label: "Flaw"
      # description: "Less reasons to like this."
      placeholder: "..."
  - type: markdown
    attributes: 
      value: "##"    
  - type: textarea
    id: hint
    attributes:
      label: "Hint"
      placeholder: "..."
  - type: dropdown
    id: env
    attributes:
      label: Environment
      description: You may select more than one.
      multiple: true
      options:
        - MacOS
        - Linux
        - Windows
        - Chrome
        - FireFox
        - Safari
        - Edge
        - Python
        - JavaScript
        - Julia
        - Java
        - R
