title: Toolstore
labels: ["tool"]
body:
  - type: checkboxes
    attributes:
      label: Pros
      options:
        - label: This one!
        - label: I won't stop you if you check this one, too
        - label: Other
          placeholder: "Enter another advantage"
