title: Toolstore
labels: ["tool"]
body:
  - type: checkboxes
    id: pros
    attributes:
      label: Pros
      description: You may select more than one.
      options:
        - label: Performance
        - label: Ease of use
        - label: Cost-effective
        - label: Feature-rich
        - label: Scalability
        - label: Security
  - type: input
    id: more
    attributes:
      label: Other
      description: "Moer reasons to like this"
      placeholder: "[ ... ]"
    validations:
      required: true
